version: "3.9"
services: 

  ros:
    container_name: ros
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  
    volumes:
      - ./${WORKSPACE}:${USERHOME}/${WORKSPACE}   # 현재 디렉토리 기본으로 연결 //원하는 경로로 바꿀 수 있음
      - ~/.ssh:${USERHOME}/.ssh  # 홈디렉토리에 있는 .ssh 연결
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # 디스플레이 연결 (GUI 프로그램 실행하기 위해)
      - /dev:/dev  #usb등의 장치 연결
    ports:
      - "11311:11311"
      - "9090:9090" #rosbridge
      - "11315:11315" #web_video
    command:
      - roscore
    restart: always
    stdin_open: true
    privileged: true
    tty: true
    devices:
      - /dev:/dev
    group_add:
      - video
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=$DISPLAY
  
  # test web 사용하려면 주석해제
  # py-web:
  #   container_name: py-web
  #   build:
  #     context: .
  #     dockerfile: DockerfilePy
  #   volumes:
  #     - ./${WORKSPACE}:${USERHOME}/${WORKSPACE}   # 현재 디렉토리 기본으로 연결 //원하는 경로로 바꿀 수 있음
  #   ports:
  #     - "8000:8000" #web server
  #   environment:
  #     - "PYTHONUNBUFFERED=1"

# 도커 up 전에 xhost + 해줄 것
# X11로 실행하지말고 Wayland 디스플레이 서버로 실행할 것
