version: "3.9"
services: 

  ros:
    container_name: ros
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  
    volumes:
      - ./${WORKSPACE}:${USERHOME}/${WORKSPACE}   # 현재 디렉토리 기본으로 연결 //원하는 경로로 바꿀 수 있음
      - ~/.ssh:${USERHOME}/.ssh  # 홈디렉토리에 있는 .ssh 연결
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # 디스플레이 연결 (GUI 프로그램 실행하기 위해)
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev  #usb등의 장치 연결
    ports:
      - "11311:11311"
    # command:
    #   - roscore  ## command가 안먹힘 좀 더 테스트 필요
    stdin_open: true
    privileged: true
    tty: true
    runtime: nvidia  ## nivia 용 (apt install -y nvidia-docker2 이 설치 후 docker재시작)
    devices:
      - /dev:/dev
    group_add:
      - video
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 #nvidia
      - XAUTHORITY=/tmp/.docker.xauth

## amd radeon 은 environment의 ROS_MASTER_URI=http://localhost:11311, DISPLAY=$DISPLAY만 적용하면 됨
## 성공! X11로 실행하지말고 Wayland 디스플레이 서버로 실행할 것
