services: 

  ros2:
    container_name: ${COMPOSE_PROJECT_NAME}_ros2
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  
    volumes:
      - ./${WORKSPACE}:${USERHOME}/${WORKSPACE}   # 현재 디렉토리 기본으로 연결 //원하는 경로로 바꿀 수 있음
      - ./${WORKSPACE_WEB}:${USERHOME}/${WORKSPACE_WEB}
      - ~/.ssh:${USERHOME}/.ssh  # 홈디렉토리에 있는 .ssh 연결
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # 디스플레이 연결 (GUI 프로그램 실행하기 위해)
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /sys:/sys:ro ## network관련
      - /var/run/dbus:/var/run/dbus:ro
      - /dev:/dev  #usb등의 장치 연결
    ports:
      - "${API_PORT}:${API_PORT}" ## for api . check out env
      - "${WEB_PORT}:${WEB_PORT}" 
    command: tail -f /dev/null # dev
    restart: always  ## when need to restart after reboot (of course it starts always)
    network_mode: host
    hostname: localhost
    stdin_open: true
    privileged: true
    tty: true
    devices:
      - /dev:/dev
    group_add:
      - video
      - audio
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 #nvidia
      - XAUTHORITY=/tmp/.docker.xauth
