services: 

  ros2:
    container_name: ${COMPOSE_PROJECT_NAME}_ros2
    build: 
      context: .  # 현재 디렉토리
      dockerfile: Dockerfile  
    volumes:
      - ./${WORKSPACE}:${USERHOME}/${WORKSPACE}   # 현재 디렉토리 기본으로 연결 //원하는 경로로 바꿀 수 있음
      - ./${WORKSPACE_WEB}:${USERHOME}/${WORKSPACE_WEB}
      - ~/.ssh:${USERHOME}/.ssh  # 홈디렉토리에 있는 .ssh 연결
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # 디스플레이 연결 (GUI 프로그램 실행하기 위해)
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /sys:/sys:ro ## network관련
      - /var/run/dbus:/var/run/dbus:ro
      - /dev:/dev  #usb등의 장치 연결
    ports:
      - "9090:9090" #rosbridge
      - "11315:11315" #web_video
    command: tail -f /dev/null # dev
    restart: always  ## when need to restart after reboot (of course it starts always)
    network_mode: host
    hostname: localhost
    stdin_open: true
    privileged: true
    tty: true
    devices:
      - /dev:/dev
    group_add:
      - video
      - audio
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1 #nvidia
      - XAUTHORITY=/tmp/.docker.xauth
    networks:
      - ros2-web

  web:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    ports: 
      - "${WEB_PORT}:80"
    volumes: 
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  ## 서버배포시에는 prod ##로컬 개발시는 dev (env)
        - ./web_src:/var/www/html  # app 디렉토리도 생성한다해서 도커 nginx 서버와 매칭
    depends_on:
      - php
    links: # Explicitly link the service name # prevent from race condition
      - php
    networks:
      - ros2-web

  mysql:
    image: mariadb:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306  ## 외부로 expose 안 되게 설정
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}  # .env
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_ID}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      SERVICE_TAGS: dev 
      TZ: Asia/Seoul
    volumes:
      - ./mysqldata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ros2-web

  php:
    # image: php:fpm #이렇게만 적으면 가장 최신버전을 받는다. Dockerfile 에서 받는다 
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:  # 위의 image는 제거
      context: .  # 현재 디렉토리
      dockerfile: php.Dockerfile
    volumes:
      - ./web_src:/var/www/html  #이제 php를 app 디렉토리로 연결
    restart: always
    depends_on:
      - ros2
      - mysql
    ports: 
      # - "9000:9000"
    networks:
      - ros2-web

  composer:
    image: composer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_composer
    volumes:
      - ./src:/var/www/html  
    working_dir: /var/www/html # 컨테이너 어디에 파일들이 있을 지를 결정
    networks:
      - ros2-web
    #$ docker-compose run --rm composer require tailwindcss(필요한라이브러리)

  npm:
    image: node:latest
    container_name: ${COMPOSE_PROJECT_NAME}_npm
    volumes: 
      - ./web_src:/var/www/html
    working_dir: /var/www/html/web_motor ## project
    networks:
      - ros2-web
    # entrypoint: ['npm']  ## npm 컨테이너에서 다른 명령어를 쳐야할 경우 주석을 해제하고 docker compose up을 다시한다 (예 npm 명령어로 시작하는 경우가 아닌 경우: npx)
    # $ docker-compose run -rm npm install
  
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_artisan
    volumes:
      - ./src:/var/www/html
    depends_on: # dependency 필요 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan'] # Added 'php' before '/var/www/html/artisan'
    networks: 
      - ros2-web
    # docker-compose run --rm artisan migrate 로 하면 된다!

networks:
  ros2-web:
