#!/bin/bash
source ./scripts/include/read_sr

### build 단계에서 host 의 volume 에서 수정이 불가능하므로  
### 의존성 정도만 설치해준다. 이것은 build 후에도 계속되고, ros2_ws 에서는 compose up 이후 한번만 빌드를 하게 되면 
### host에 계속 남아 있기 때문에 의존성 및 git clone만 해준다.
### 단, compose up 이 된 후에 깃 클론된 패키지는 docker_ros2_tb_ws 으로 이동시킨 후 빌드해준다. (컨테이너 실행 후)

## dependency
echo $password | sudo -S apt update &&
                sudo apt install ros-humble-nav2-util ros-humble-nav2-bringup ros-humble-rviz2 \
                        ros-humble-dynamixel-sdk ros-humble-turtlebot3-msgs ros-humble-cartographer-ros \
                        ros-humble-hls-lfcd-lds-driver -y

git clone https://github.com/ROBOTIS-GIT/turtlebot3 -b humble-devel
